// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tmkoxpzrjzwccahzaedf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRta294cHpyanp3Y2NhaHphZWRmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ1MjQ0ODEsImV4cCI6MjA3MDEwMDQ4MX0.gKXGr0hlyepxa8ho9xV-yWm9Xt-A_XWEbi_nTWPQyBI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});